Add [bchk_pass] and [bchk_fail].
These are utilitiy functions to send to stderr a message with
a green/red PASS/FAIL prefix.

diff --git a/insitu.d/insitu b/insitu.d/insitu
--- a/insitu.d/insitu
+++ b/insitu.d/insitu
@@ -37,3 +37,16 @@ cd ${BCHK_ROOT}/source.d
 for script in $(/bin/ls [0-9]* | sort); do
     _myborg source  $PWD/$script
 done
+
+
+bchk_pass () { 
+    echo "$(tput bold)$(tput setaf 15)$(tput setab 2)  PASS  $(tput sgr0) $*" >&2; 
+    return 0
+}
+bchk_fail () { 
+    echo "$(tput bold)$(tput setaf 15)$(tput setab 1)  FAIL  $(tput sgr0) $*" >&2; 
+    return 0
+}
+
+
+
